"use client";
import { useState, useEffect } from "react";
const CHATBOT_URL = "https://chat-bot-yacht-management.vercel.app";
export default function AssistenceButton() {
  const [open, setOpen] = useState(false);
  const [loaded, setLoaded] = useState(false);
  useEffect(() => { const h = (e: KeyboardEvent) => { if (e.key === "Escape") setOpen(false); }; window.addEventListener("keydown", h); return () => window.removeEventListener("keydown", h); }, []);
  useEffect(() => { document.body.style.overflow = open ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [open]);
  const btn = !open && (<button onClick={() => { setOpen(true); setLoaded(false); }} style={{ position: "fixed", bottom: 96, right: 28, zIndex: 199, display: "flex", alignItems: "center", gap: 9, padding: "12px 20px", background: "linear-gradient(135deg, #023E8A, #0077B6, #00B4D8)", color: "white", border: "none", borderRadius: 50, fontSize: 13, fontWeight: 600, cursor: "pointer", fontFamily: "inherit", boxShadow: "0 4px 20px rgba(0,119,182,0.35)" }}>{"\u2693"} Assistence</button>);
  const modal = open && (<div onClick={() => setOpen(false)} style={{ position: "fixed", inset: 0, zIndex: 9998, background: "rgba(12,28,48,0.55)", backdropFilter: "blur(6px)", display: "flex", alignItems: "center", justifyContent: "center", padding: 20 }}><div onClick={(e) => e.stopPropagation()} style={{ position: "relative", width: "100%", maxWidth: 480, height: "min(680px, 85vh)", background: "#FFF", borderRadius: 18, overflow: "hidden", boxShadow: "0 25px 60px rgba(0,60,130,0.25)", display: "flex", flexDirection: "column" }}><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "12px 16px", background: "linear-gradient(135deg, #023E8A, #0077B6)", flexShrink: 0 }}><div style={{ display: "flex", alignItems: "center", gap: 10 }}><span style={{ fontSize: 18 }}>{"\u2693"}</span><div><div style={{ fontSize: 13, fontWeight: 700, color: "white" }}>Yacht Support Assistant</div><div style={{ fontSize: 11, color: "rgba(255,255,255,0.65)" }}>AI-powered diagnostics</div></div></div><button onClick={() => setOpen(false)} style={{ width: 28, height: 28, display: "flex", alignItems: "center", justifyContent: "center", background: "rgba(255,255,255,0.15)", border: "none", borderRadius: 6, cursor: "pointer", color: "white", fontSize: 16 }}>{"\u2715"}</button></div><iframe src={CHATBOT_URL} title="Yacht Support Assistant" onLoad={() => setLoaded(true)} style={{ flex: 1, width: "100%", border: "none", background: "#F7F8FA" }} allow="microphone; clipboard-write" sandbox="allow-scripts allow-same-origin allow-forms allow-popups" /></div></div>);
  return (<>{btn}{modal}</>);
}
